### ISSUE TITLE
Adding default icons

### ISSUE THREAD

**Issue by christoph-r** [DRIVER-EU/TheHagueData#1]
Hi Erik,
could you please add a default icon to each GeoJSON file?
So we would have a consistent look and feel in all tools.

Thanks in advance.
  Christoph

**Comment by erikvullings** [comment]
Electricity (powerstation from):
https://github.com/TNOCS/csWeb-sim/tree/master/public/images/Electricity

Risk:
https://github.com/TNOCS/csWeb-sim/blob/master/public/images/Risico/28-Risico-.png

Flooding:
https://github.com/TNOCS/csWeb-sim/blob/master/public/images/flooding.png

City
https://github.com/TNOCS/csWeb-sim/blob/master/public/images/gemeente.png

Other links:
https://github.com/TNOCS/csWeb-sim/tree/master/public/images

Hospital -> ziekenhuis
https://github.com/TNOCS/csWeb-sim/blob/master/public/images/ziekenhuis.png

Care institution -> verzorgingstehuis
https://github.com/TNOCS/csWeb-sim/blob/master/public/images/verzorgingstehuis.png

Communication -> c2000
https://github.com/TNOCS/csWeb-sim/blob/master/public/images/c2000.png
